(WIP) feat: add an option to configure log-pilot to ignore or/and only handle containers from specified namespaces
caicloud/log-pilot pull request #9
Opened 2019-01-10 10:08 UTC by lichuan0620

**What this PR does / why we need it**:

In order to support dedicated ES for system log, it is necessary for containers from different namespaces to be outputted to different ES. This PR adds an option to configure log-pilot to ignore or/and only handle containers from certain namespaces via command argument. 

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @caitong93 @supereagle 

**Release note**:

```release-note
NONE
```

2019-01-10 10:12 UTC, lichuan0620 commented
Just a draft. Not tested.

@caitong93 feedback?

2019-01-14 02:28 UTC, caitong93 commented
@lichuan0620 
You can do filtering at https://github.com/caicloud/log-pilot/blob/master/pilot/discovery/discovery.go#L252

2019-01-14 03:01 UTC, lichuan0620 commented
@caitong93 PTAL

2019-01-14 03:26 UTC, caitong93 requested changes

2019-01-14 03:26 UTC, caitong93 commented on pilot/configurer/filebeat/filebeat.go
> +func (c *filebeatConfigurer) IsResponsible(namespace string) bool {
This can be moved to discovery

2019-01-15 03:42 UTC, caitong93 approved these changes

2019-01-23 03:16 UTC, lichuan0620 commented
tested, PTAL
@caitong93 @supereagle

2019-01-23 08:31 UTC, caitong93 commented
/lgtm

2019-01-23 08:33 UTC, merged